server: 
  port: ${SERVER_PORT:8087}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/}
    
spring: 
  application: 
    name: cloud-stream-annotation-consumer
    
  cloud:
    stream:
      bindings:
        approved:
          destination: queue.loan.approved
          group: approved-loan
        declined:
          destination: queue.loan.declined
          group: declined-loan


  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    port: ${RABBITMQ_SERVER_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}    